### ISSUE TITLE
Crash on overridden typed properties when base has no value

### ISSUE THREAD

**Issue by rr-** [PyCQA/astroid#419] opened 2017-03-25 07:41 UTC
### Steps to reproduce

```python3
class Command:
    name: str

class PlayCommand(Command):
    name = 'play'
```

### Current behavior

```
Traceback (most recent call last):
  File "/home/rr-/.local/bin//pylint", line 11, in <module>
    load_entry_point('pylint==2.0.0', 'console_scripts', 'pylint')()
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/checkers/classes.py", line 536, in visit_classdef
    self._check_bases_classes(node)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/checkers/classes.py", line 1114, in _check_bases_classes
    unimplemented_abstract_methods(node, is_abstract).items(),
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/checkers/utils.py", line 547, in unimplemented_abstract_methods
    infered = safe_infer(obj)
  File "/home/rr-/.local/lib/python3.6/site-packages/pylint/checkers/utils.py", line 767, in safe_infer
    value = next(inferit)
  File "/home/rr-/.local/lib/python3.6/site-packages/astroid/decorators.py", line 85, in wrapped
    res = next(generator)
  File "/home/rr-/.local/lib/python3.6/site-packages/astroid/bases.py", line 93, in _infer_stmts
    context.lookupname = stmt._infer_name(frame, name)
AttributeError: 'NoneType' object has no attribute '_infer_name'
```

### Expected behavior

```
************* Module test
R:  1, 0: Too few public methods (0/1) (too-few-public-methods)
R:  4, 0: Too few public methods (0/1) (too-few-public-methods)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 9.38/10, -4.38)
```

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

`1.5.0`

**Comment by rr-** [comment] 2017-03-25 07:44
Switching to a slightly more verbose idiom:

```
class Command:
    @property
    def name(self) -> str:
        raise NotImplementedError()
```

as well as providing default value:

```
class Command:
    name: str = 'INVALID'
```

works, nonetheless `astroid` shouldn't crash like this.

**Comment by rogalski** [comment] 2017-03-27 20:21
Possible dupe of PyCQA/pylint#1389

**Closed** 2017-04-02 12:55 UTC
