### ISSUE TITLE
astroid cannot find module if source file is a symlink?

### ISSUE THREAD

**Issue by stphnlyd** [PyCQA/astroid#556] opened 2018-06-08 10:17 UTC
I am using astroid 1.6.4 and get the same issue as https://github.com/PyCQA/pylint/issues/1470. And someone identified that it's related to astroid https://github.com/PyCQA/pylint/issues/1470#issuecomment-345093616

**Comment by PCManticore** [comment] 2018-06-08 21:44
This looks like a duplicate of that issue.

**Closed by PCManticore** 2018-06-08 21:44 UTC

**Comment by stphnlyd** [comment] 2018-06-09 04:58
but the fix shall be in astroid but not pylint I think.
