### ISSUE TITLE
AttributeError: 'Attribute' object has no attribute 'lookup'

### ISSUE THREAD

**Issue by zidarsk8** [PyCQA/astroid#626] opened 2018-12-03 21:27 UTC
### Steps to reproduce

I have tried to narrow down this bug but due to sqlalchemy magic this is as low as I got:

#### Only in python 3 environment:

1. run `pip install -U sqlalchemy==1.2.14` # or any version after 0.9.0 I'm just using the latest
2. Create file linttest.py
```python
from sqlalchemy.ext.declarative import declared_attr

class MyModel():

  @declared_attr
  def title(cls):
    pass

  def my_function(self):
    value = getattr(self, 'title')
    return value == 5  # changing this line to `getattr(self, 'title') == 5` works
```
3. run pylint on this file
```
$ pylint pylinttest.py
************* Module pylinttest
pylinttest.py:10:2: E0213: Method should have "self" as first argument (no-self-argument)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function register_builtin_transform.<locals>._transform_wrapper at 0x7f74cb851bf8>, <Call l.14 at 0x7f74cb577da0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 181, in getattr
    values = self._proxied.instance_attr(name, context)
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 2310, in instance_attr
    target=self, attribute=name, context=context
astroid.exceptions.AttributeInferenceError: 'title' not found on <ClassDef.MyModel l.7 at 0x7f74cb577a58>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 215, in igetattr
    get_attr = self.getattr(name, context, lookupclass=False)
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 193, in getattr
    ) from exc
astroid.exceptions.AttributeInferenceError: 'title' not found on <Instance of pylinttest.MyModel at 0x140139593100760>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1608, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 938, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1071, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1154, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/site-packages/pylint/utils.py", line 1266, in walk
    cb(astroid)
  File "/usr/local/lib/python3.7/site-packages/pylint/checkers/base.py", line 2153, in visit_compare
    self._check_callable_comparison(node)
  File "/usr/local/lib/python3.7/site-packages/pylint/checkers/base.py", line 2137, in _check_callable_comparison
    for operand in (left_operand, right_operand)
  File "/usr/local/lib/python3.7/site-packages/pylint/checkers/base.py", line 2138, in <genexpr>
    if isinstance(utils.safe_infer(operand), bare_callables)
  File "/usr/local/lib/python3.7/site-packages/pylint/checkers/utils.py", line 1073, in safe_infer
    value = next(inferit)
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 135, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/usr/local/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 128, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 135, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.7/site-packages/astroid/node_classes.py", line 348, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/astroid/__init__.py", line 93, in _inference_tip_cached
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/astroid/brain/brain_builtin_inference.py", line 132, in _transform_wrapper
    result = transform(node, context=context)
  File "/usr/local/lib/python3.7/site-packages/astroid/brain/brain_builtin_inference.py", line 415, in infer_getattr
    return next(obj.igetattr(attr, context=context))
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 227, in igetattr
    yield from self._wrap_attr(attrs, context)
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 235, in _wrap_attr
    if _is_property(attr):
  File "/usr/local/lib/python3.7/site-packages/astroid/bases.py", line 85, in _is_property
    module, _ = base_class.lookup(base_class.name)
AttributeError: 'Attribute' object has no attribute 'lookup'
```

### Current behavior

Attribute error is raised when analyzing title attribute.

### Expected behavior

Pylint should finish normally 

### 2.1.0 , I also tried with version 2.0, any earlier version raises a different issue
```
# pylint --version
pylint 2.2.2
astroid 2.1.0
Python 3.7.1 (default, Nov 16 2018, 22:26:09)
[GCC 6.3.0 20170516]
```

**Comment by PCManticore** [comment] 2018-12-04 07:12
Thanks for the report!

**Comment by PCManticore** [comment] 2018-12-04 07:34
Thanks @zidarsk8 ! Fixed in the the latest commit. Unfortunately I couldn't reproduce it without `sqlalchemy` so there's no test for it.

**Closed** 2018-12-04 07:34 UTC
Labels: bug, crash
