### ISSUE TITLE
 AttributeError: 'AssignAttr' object has no attribute 'qname'

### ISSUE THREAD

**Issue by alex-hutton** [PyCQA/astroid#464] opened 2017-11-03 05:12 UTC
I frequently, but not always, see `AttributeError: 'AssignAttr' object has no attribute 'qname'` when running pylint on my sourcecode.

Unfortunately I was unable to find any clues as to why this is happening. I have tried pylint 1.7.4 and pylint 1.6.5. I am using astroid 1.5.3.

Please advise how I can investigate this further.

### Steps to reproduce
Run pylint on sourcecode.

### Current behavior
See attached backtrace.

[error.txt](https://github.com/PyCQA/astroid/files/1440130/error.txt)

### Expected behavior
pylint runs normally.

**Comment by PCManticore** [comment] 2017-11-11 11:50
Hi @alex-hutton 

Thanks for submitting an issue. What would be helpful now would be a reproducing case for this problem, even if it is a blob of code, having a code that we can run against to see where the failure is would be most useful.

**Comment by PCManticore** [comment] 2017-12-15 09:28
Closing this. I'm noticing the stacktraces has traces of a pylint plugin, which might also be a contributing factor to this error.

**Closed by PCManticore** 2017-12-15 09:28 UTC
Labels: needs-reproduction

**Comment by sbdchd** [comment] 2019-11-01 13:25
I'm experiencing this issue as well, originally we thought it was limited to `pylint-django` but after fixing the error in that package the issue is popping up in pylint via astroid.

Reproduction is hard because running the CI job again usually fixes the problem.

It seems that one of the possible return types of the `.infer()` method is `AssignAttr`, which doesn't have a `qname` method.

I'm not to familiar with the code but maybe something like would fix it:

```diff
diff --git a/astroid/scoped_nodes.py b/astroid/scoped_nodes.py
index d02b6534..0cf39214 100644
--- a/astroid/scoped_nodes.py
+++ b/astroid/scoped_nodes.py
@@ -1752,6 +1752,8 @@ def _is_metaclass(klass, seen=None):
     for base in klass.bases:
         try:
             for baseobj in base.infer():
+                if not hasattr(baseobj, 'qname'):
+                    continue
                 baseobj_name = baseobj.qname()
                 if baseobj_name in seen:
                     continue
``` 

<details closed>

<summary> stack trace </summary>

```
Traceback (most recent call last):
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/pylint/checkers/classes.py", line 731, in visit_classdef
    if node.type == "class" and has_known_bases(node):
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1760, in _class_type
    if _is_metaclass(klass):
  File "/home/circleci/.cache/pypoetry/virtualenvs/backend-py3.6/lib/python3.6/site-packages/astroid/scoped_nodes.py", line 1730, in _is_metaclass
    baseobj_name = baseobj.qname()
AttributeError: 'AssignAttr' object has no attribute 'qname'
```

</details>

**Comment by PCManticore** [comment] 2019-11-08 16:36
@sbdchd From your traceback it seems you are using `pylint_plugin_utils` and I presume that's the culprit as it must be doing something with the AST. If we can get a sample that reproduces with `pylint` without any plugins that would be great, as we can have a way to reproduce it. Otherwise I feel it must be something related to `pylint_plugin_utils` and / or `pylint_django`.
