### ISSUE TITLE
Performance regressions with 2.5.7

### ISSUE THREAD

**Issue by nelfin** [PyCQA/astroid#1003] opened 2021-05-30 00:42 UTC
@cdce8p, @Pierre-Sassoulas, @hippo91: I meant to highlight this before there was a tagged release, but additional copies in the `InferenceContext.clone` cause some performance slowdown, especially in modules with deep inference chains. Maybe there should be additional benchmarking before `pylint` bumps it's minimum required version of `astroid`?

**Comment by benfred** [comment] 2021-06-01 18:16
I've also run into a major performance regression with astroid 2.5.7 using pylint against https://github.com/nvidia/nvtabular . 

With astroid 2.5.6 I can run ```pylint nvtabular/workflow.py``` in about 10 seconds, but with astroid 2.5.7 pylint has been running for 40+ minutes without finishing.  I've posted a [flamegraph here](https://gist.githubusercontent.com/benfred/458b0783ff97bd15225acf26c1d2e8c5/raw/9c66cde5f5a6664aa39118d4a68e7fcfc78517e2/astroid.svg) showing the callstack

**Comment by nelfin** [comment] 2021-06-02 00:13
@benfred: I don't have a conda install so I wasn't able to work with `nvtabular`, but I followed its dependency chain up one level to `cudf` and I was able to get some pathological slowdown with files like `cudf/python/cudf/cudf/core/series.py`

**Comment by benfred** [comment] 2021-06-02 01:58
thanks for looking into this @nelfin! 

I peaked a bit at the slowdown I was seeing with py-spy, and I can also verify that the problem seems to be in the cudf dependency. Running ```py-spy dump --locals -p PID``` shows slow processing of cudf.core.index at one point and cudf.core.dataframe at another - with frames like this on the stack trace: 

```
.. 
    ast_from_file (astroid/manager.py:100)
        Arguments::
            self: <AstroidManager at 0x7fe28efa9400>
            filepath: "/home/ben/miniconda3/envs/nvtabular_cudf19/lib/python3.8/site-packages/cudf/core/index.py"
            modname: "cudf.core.index"
            fallback: False
            source: True
        Locals::
            AstroidBuilder: <type at 0x5636e352d8c0>
    ast_from_module_name (astroid/manager.py:192)
        Arguments::
            self: <AstroidManager at 0x7fe28efa9400>
            modname: "cudf.core.index"
            context_file: None
        Locals::
            found_spec: ("index", <ModuleType at 0x7fe28f8f0f10>, ...)
...
```

**Comment by Pierre-Sassoulas** [comment] 2021-06-02 14:51
Probably related I encountered a RecursionError on code I can't share:

```
Exception on node <Assign l.144 at 0x7f0726cde610> in file '/builds/a.py'
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.8/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/run.py", line 381, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 873, in check
    self._check_files(
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 907, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 933, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/local/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1112, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/usr/local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/usr/local/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1240, in visit_assign
    self._check_consider_using_with_instead_assign(node)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1274, in _check_consider_using_with_instead_assign
    inferred = utils.safe_infer(assigned.func)
  File "/usr/local/lib/python3.8/site-packages/pylint/checkers/utils.py", line 1204, in safe_infer
    value = next(infer_gen)
  File "/usr/local/lib/python3.8/site-packages/astroid/node_classes.py", line 366, in infer
    yield from self._infer(context, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 135, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 99, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/node_classes.py", line 380, in infer
    for i, result in enumerate(generator):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 135, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 99, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/bases.py", line 136, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/usr/local/lib/python3.8/site-packages/astroid/node_classes.py", line 380, in infer
    for i, result in enumerate(generator):
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 135, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.8/site-packages/astroid/decorators.py", line 96, in wrapped
    generator = _func(node, context, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/astroid/inference.py", line 269, in infer_import_from
    module = self.do_import_module()
  File "/usr/local/lib/python3.8/site-packages/astroid/mixins.py", line 100, in do_import_module
    return mymodule.import_module(
  File "/usr/local/lib/python3.8/site-packages/astroid/scoped_nodes.py", line 685, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 192, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/usr/local/lib/python3.8/site-packages/astroid/manager.py", line 100, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 144, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 164, in _post_build
    self.delayed_assattr(delayed)
  File "/usr/local/lib/python3.8/site-packages/astroid/builder.py", line 234, in delayed_assattr
    for inferred in node.expr.infer():
  File "/usr/local/lib/python3.8/site-packages/astroid/node_classes.py", line 366, in infer
    yield from self._infer(context, **kwargs)
...
```

**Comment by nelfin** [comment] 2021-06-03 10:33
@Pierre-Sassoulas: blowing the stack like that would be similar stuff to what we've seen before, it doesn't actually appear that there is any runaway recursion, just that inference can sometimes produce call-stacks greater than 1000 calls deep.

@benfred: would you be able to do me a favour and test a branch I've pushed on my fork? `pip install -U git+https://github.com/nelfin/astroid.git@wip/performance#egg=astroid` should work. I've gotten it to a point where it's ~4x faster than 2.5.6 on `cudf.core` as a baseline, and it passes all the 2.5.7 tests, but it's a real hack-job so I'd appreciate some real-world testing.

**Comment by benfred** [comment] 2021-06-03 18:20
@nelfin - with astroid from your branch running ```pylint nvtabular/workflow.py``` takes about 8.6 seconds, compared to about 10.6s for v2.5.6 , and >1 hour on v2.5.7 .  Not quite the 4x speedup you were seeing on cudf on it's own, but still a significant improvement . Thanks!

**Comment by Pierre-Sassoulas** [comment] 2021-06-03 18:52
I can release astroid 2.5.8 as soon as this amazing performance improvement is merged :)

**Comment by RuRo** [comment] 2021-06-05 07:21
@Pierre-Sassoulas the PR in question is marked as ready for review. Who (apart from you) should I annoy to get it merged faster? 😈

**Comment by Pierre-Sassoulas** [comment] 2021-06-05 10:13
hippo91 or cdce8p :) hippo91 already reviewed that's why I'm not pinging him here :)

**Comment by Pierre-Sassoulas** [comment] 2021-06-07 15:08
As performance got better than what they were in 2.5.6 I assume if something arise it will be handled in another more specific issue. I'm going to release 2.5.8 shortly.

**Closed by Pierre-Sassoulas** 2021-06-07 15:08 UTC
Labels: blocker, topic-performance
