### ISSUE TITLE
Do you have any plan to release a new version?

### ISSUE THREAD

**Issue by ikedaosushi** [PyCQA/astroid#886] opened 2021-01-26 01:45 UTC
Hi, astroid team. 

My team is using pylint, there is a problem with the combination of astroid==2.4.2 and pandas==1.1.5 as the following issue.
https://github.com/pandas-dev/pandas/issues/38355

In fact, this issue is fixed in astroid==master, so I'm curious whether there is a plan to release a new version of astroid.
In my observation, many developers faced the same problem, at least at that time. I believe the new release will help many🙂

I really appreciate your continuous development. Thanks.

**Comment by mihaimaruseac** [comment] 2021-01-27 17:33
TensorFlow is also blocked on a new version of astroid, via pylint.

**Comment by JamieSharpe** [comment] 2021-01-28 09:41
I'm having similar issues with conflicting dependencies.

`The conflict is caused by:
    The user requested lazy-object-proxy==1.5.2
    astroid 2.4.2 depends on lazy-object-proxy==1.4.*`

This is resolved in one of the latest commits [@744a9a8](https://github.com/PyCQA/astroid/commit/744a9a802543a46ff4c9e0727d8ea4fc83c80691).

There was a release date [marked](https://github.com/PyCQA/astroid/commit/7aff33388c5a7b165d9355cd972b0746ff1d2bc4), which was quickly [overturned](https://github.com/PyCQA/astroid/commit/9270a2105fa7ecbeeb9021c8150659c55107198f#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfb).

A new release would fix our development upgrades being blocked.

**Comment by hippo91** [comment] 2021-01-31 14:40
@PCManticore @AWhetter any idea about this?
If you agree i'll be pleased to release a new version of `astroid` and `pylint`.
There are many demands about this.

**Comment by AWhetter** [comment] 2021-01-31 18:57
I haven't kept up with what changes have gone in and whether there has been anything risky that we've done, but given that it's been such a long time since we've done a release of pylint or astroid I think doing a release soon/now seems like a good idea.

**Comment by hippo91** [comment] 2021-02-15 21:13
The new `astroid` version (1.5) has been released.

**Closed by hippo91** 2021-02-15 21:13 UTC
