### ISSUE TITLE
KeyError: 'foogle' for test suite on Python 2.7.13 on openSUSE TW and Alpine Linux

### ISSUE THREAD

**Issue by sebix** [PyCQA/astroid#439] opened 2017-05-26 18:38 UTC
### Steps to reproduce
1. Extract archive
1. Run `python -m pytest -s`

### Current behavior
`test_namespace_package_pth_support` fails:

```
[   24s] =================================== FAILURES ===================================
[   24s] ____________ AstroidManagerTest.test_namespace_package_pth_support _____________
[   24s] 
[   24s] self = <astroid.tests.unittest_manager.AstroidManagerTest testMethod=test_namespace_package_pth_support>
[   24s] 
[   24s]     def test_namespace_package_pth_support(self):
[   24s]         pth = 'foogle_fax-0.12.5-py2.7-nspkg.pth'
[   24s]         site.addpackage(resources.RESOURCE_PATH, pth, [])
[   24s]         # pylint: disable=no-member; can't infer _namespace_packages, created at runtime.
[   24s]         pkg_resources._namespace_packages['foogle'] = []
[   24s]     
[   24s]         try:
[   24s]             module = self.manager.ast_from_module_name('foogle.fax')
[   24s]             submodule = next(module.igetattr('a'))
[   24s]             value = next(submodule.igetattr('x'))
[   24s]             self.assertIsInstance(value, astroid.Const)
[   24s]             with self.assertRaises(exceptions.AstroidImportError):
[   24s]                 self.manager.ast_from_module_name('foogle.moogle')
[   24s]         finally:
[   24s]             del pkg_resources._namespace_packages['foogle']
[   24s] >           sys.modules.pop('foogle')
[   24s] E           KeyError: 'foogle'
[   24s] 
[   24s] astroid/tests/unittest_manager.py:140: KeyError
```
See the build log: https://build.opensuse.org/package/live_build_log/home:sebix:branches:devel:languages:python/python-astroid/openSUSE_Tumbleweed/x86_64

### Expected behavior
Test passes

astroid is not installed
astroid from https://files.pythonhosted.org/packages/source/a/astroid/astroid-1.5.2.tar.gz
Python 2.7.13 on openSUSE TW

**Comment by sebix** [comment] 2017-06-03 15:45
Also happens for 1.5.3

**Comment by frispete** [comment] 2017-10-09 10:41
There are more problems lurking in this area.

After changing the offending line:
```
Index: b/astroid/tests/unittest_manager.py
===================================================================
--- a/astroid/tests/unittest_manager.py
+++ b/astroid/tests/unittest_manager.py
@@ -137,7 +137,7 @@ class AstroidManagerTest(resources.SysPa
                 self.manager.ast_from_module_name('foogle.moogle')
         finally:
             del pkg_resources._namespace_packages['foogle']
-            sys.modules.pop('foogle')
+            sys.modules.pop('foogle', None)
 
     def _test_ast_from_zip(self, archive):
         origpath = sys.path[:]
```
it runs into another issue:
```
[   19s] =================================== FAILURES ===================================
[   19s] ____________ AstroidManagerTest.test_namespace_package_pth_support _____________
[   19s] 
[   19s] self = <astroid.tests.unittest_manager.AstroidManagerTest testMethod=test_namespace_package_pth_support>
[   19s] 
[   19s]     def test_namespace_package_pth_support(self):
[   19s]         pth = 'foogle_fax-0.12.5-py2.7-nspkg.pth'
[   19s]         site.addpackage(resources.RESOURCE_PATH, pth, [])
[   19s]         # pylint: disable=no-member; can't infer _namespace_packages, created at runtime.
[   19s]         pkg_resources._namespace_packages['foogle'] = []
[   19s]     
[   19s]         try:
[   19s] >           module = self.manager.ast_from_module_name('foogle.fax')
[   19s] 
[   19s] astroid/tests/unittest_manager.py:132: 
[   19s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   19s] 
[   19s] self = <astroid.manager.AstroidManager object at 0x7fcb46a2d210>
[   19s] modname = 'foogle.fax', context_file = None
[   19s] 
[   19s]     def ast_from_module_name(self, modname, context_file=None):
[   19s]         """given a module name, return the astroid object"""
[   19s]         if modname in self.astroid_cache:
[   19s]             return self.astroid_cache[modname]
[   19s]         if modname == '__main__':
[   19s]             return self._build_stub_module(modname)
[   19s]         old_cwd = os.getcwd()
[   19s]         if context_file:
[   19s]             os.chdir(os.path.dirname(context_file))
[   19s]         try:
[   19s]             found_spec = self.file_from_module_name(modname, context_file)
[   19s]             # pylint: disable=no-member
[   19s]             if found_spec.type == spec.ModuleType.PY_ZIPMODULE:
[   19s]                 # pylint: disable=no-member
[   19s]                 module = self.zip_import_data(found_spec.location)
[   19s]                 if module is not None:
[   19s]                     return module
[   19s]     
[   19s]             elif found_spec.type in (spec.ModuleType.C_BUILTIN,
[   19s]                                      spec.ModuleType.C_EXTENSION):
[   19s]                 # pylint: disable=no-member
[   19s]                 if (found_spec.type == spec.ModuleType.C_EXTENSION
[   19s]                         and not self._can_load_extension(modname)):
[   19s]                     return self._build_stub_module(modname)
[   19s]                 try:
[   19s]                     module = modutils.load_module_from_name(modname)
[   19s]                 except Exception as ex: # pylint: disable=broad-except
[   19s]                     util.reraise(exceptions.AstroidImportError(
[   19s]                         'Loading {modname} failed with:\n{error}',
[   19s]                         modname=modname, path=found_spec.location, error=ex))
[   19s]                 return self.ast_from_module(module, modname)
[   19s]     
[   19s]             elif found_spec.type == spec.ModuleType.PY_COMPILED:
[   19s]                 raise exceptions.AstroidImportError(
[   19s]                     "Unable to load compiled module {modname}.",
[   19s]                     # pylint: disable=no-member
[   19s]                     modname=modname, path=found_spec.location)
[   19s]     
[   19s]             elif found_spec.type == spec.ModuleType.PY_NAMESPACE:
[   19s]                 return self._build_namespace_module(modname,
[   19s]                                                     # pylint: disable=no-member
[   19s]                                                     found_spec.submodule_search_locations)
[   19s]     
[   19s]             # pylint: disable=no-member
[   19s]             if found_spec.location is None:
[   19s]                 raise exceptions.AstroidImportError(
[   19s]                     "Can't find a file for module {modname}.",
[   19s]                     modname=modname)
[   19s]     
[   19s]             # pylint: disable=no-member
[   19s]             return self.ast_from_file(found_spec.location, modname, fallback=False)
[   19s]         except exceptions.AstroidBuildingError as e:
[   19s]             for hook in self._failed_import_hooks:
[   19s]                 try:
[   19s]                     return hook(modname)
[   19s]                 except exceptions.AstroidBuildingError:
[   19s]                     pass
[   19s] >           raise e
[   19s] E           AstroidImportError: Failed to import module foogle.fax with error:
[   19s] E           No module named foogle.fax.
[   19s] 
[   19s] astroid/manager.py:161: AstroidImportError
[   19s] ========= 1 failed, 625 passed, 90 skipped, 7 xfailed in 4.41 seconds ==========
```
Hmm, strange.

Why doesn't this stick out in tox testing?

**Comment by frispete** [comment] 2017-10-09 10:47
While the above issues happen with all tested environments on OBS, astroid 1.5.3 gained another issue with just openSUSE 42.3:

```
[   81s] =================================== FAILURES ===================================
[   81s] _____________________ NonRegressionTests.test_ssl_protocol _____________________
[   81s] 
[   81s] self = <astroid.tests.unittest_regrtest.NonRegressionTests testMethod=test_ssl_protocol>
[   81s] 
[   81s]     def test_ssl_protocol(self):
[   81s]         node = extract_node('''
[   81s]             import ssl
[   81s]             ssl.PROTOCOL_TLSv1
[   81s]             ''')
[   81s]         inferred = next(node.infer())
[   81s] >       self.assertIsInstance(inferred, nodes.Const)
[   81s] E       AssertionError: Uninferable is not an instance of <class 'astroid.node_classes.Const'>
[   81s] 
[   81s] astroid/tests/unittest_regrtest.py:308: AssertionError
[   81s] ========= 1 failed, 625 passed, 89 skipped, 7 xfailed in 10.97 seconds =========
```
You can check these builds here:
https://build.opensuse.org/package/show/home:frispete:python/python-astroid?expand=1

I've left the patch unapplied in order to demonstrate this very issue.

**Comment by PCManticore** [comment] 2017-10-12 08:36
I have no idea what is happening here, nor do I have an OpenSuse machine to check this out. The `ssl` test failure is probably related to the [ssl brain plugin](https://github.com/PyCQA/astroid/blob/9d94babb2e968c5a343218a48684a9529cbab568/astroid/brain/brain_ssl.py#L10), either the `_ssl` module is not available in that build or it is different than what the brain plugin is describing. I also can't reproduce the namespace package test, since it works with `tox` and also on Travis.

**Comment by NHellFire** [comment] 2017-11-19 21:01
I'm also seeing this with v1.5.3 on Alpine Linux with Python 2.7.14 and 3.6.3.

After fixing `KeyError: 'foogle'`, I'm then getting `No module named foogle.fax`

**Comment by sebix** [comment] 2017-12-04 20:12
@NHellFire Thanks for confirmation, I adapted the title accordingly.

**Comment by brycepg** [comment] 2018-02-13 05:17
I can repro this on Linux only with tox + pytest. Doesn't reproduce for me with just pytest

**Comment by brycepg** [comment] 2018-02-13 05:43
@sebix Can you confirm `python -m pytest -s --pyargs astroid` fixes this issue?

**Comment by sebix** [comment] 2018-02-13 11:52
> @sebix Can you confirm python -m pytest -s --pyargs astroid fixes this issue?

No.

```
> python -m pytest -s --pyargs astroid
==================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/ele/Downloads/astroid-1.6.1, inifile: pytest.ini
collected 750 items                                                                                                                                          

astroid/tests/unittest_brain.py ..s..............s...................s...                                                                              [  5%]
astroid/tests/unittest_brain_numpy.py ..........                                                                                                       [  6%]
astroid/tests/unittest_builder.py ......................s.........................sssssssssss....                                                      [ 15%]
astroid/tests/unittest_helpers.py ..........ss.                                                                                                        [ 16%]
astroid/tests/unittest_inference.py ....................................................................s...............x.s.........x................. [ 32%]
..........x.............ss.x.s..........................ssssssss..x........................................................sss.....s..                 [ 50%]
astroid/tests/unittest_lookup.py .....................                                                                                                 [ 52%]
astroid/tests/unittest_manager.py ....................sFF...                                                                                           [ 56%]
astroid/tests/unittest_modutils.py ....................................                                                                                [ 61%]
astroid/tests/unittest_nodes.py ss....s............................sssss..........ss.....                                                              [ 68%]
astroid/tests/unittest_object_model.py x............ssx.s.....s...ss                                                                                   [ 72%]
astroid/tests/unittest_objects.py ....s..............                                                                                                  [ 75%]
astroid/tests/unittest_peephole.py ....                                                                                                                [ 75%]
astroid/tests/unittest_protocols.py ss..sss..                                                                                                          [ 76%]
astroid/tests/unittest_python3.py ssssssssssssssssssssssss                                                                                             [ 80%]
astroid/tests/unittest_raw_building.py .......ss                                                                                                       [ 81%]
astroid/tests/unittest_regrtest.py .........s..........                                                                                                [ 83%]
astroid/tests/unittest_scoped_nodes.py ..................sss.s.........s..s.......s......s.........................................................    [ 98%]
astroid/tests/unittest_transforms.py ........                                                                                                          [ 99%]
astroid/tests/unittest_utils.py .....                                                                                                                  [100%]

========================================================================== FAILURES ==========================================================================
____________________________________________________ AstroidManagerTest.test_namespace_and_file_mismatch _____________________________________________________

self = <astroid.tests.unittest_manager.AstroidManagerTest testMethod=test_namespace_and_file_mismatch>

    def test_namespace_and_file_mismatch(self):
        filepath = unittest.__file__
        ast = self.manager.ast_from_file(filepath)
        self.assertEqual(ast.name, 'unittest')
        pth = 'foogle_fax-0.12.5-py2.7-nspkg.pth'
        site.addpackage(resources.RESOURCE_PATH, pth, [])
        pkg_resources._namespace_packages['foogle'] = [] # pylint: disable=no-member
        try:
            with self.assertRaises(exceptions.AstroidImportError):
                self.manager.ast_from_module_name('unittest.foogle.fax')
        finally:
            del pkg_resources._namespace_packages['foogle'] # pylint: disable=no-member
>           sys.modules.pop('foogle')
E           KeyError: 'foogle'

astroid/tests/unittest_manager.py:153: KeyError
___________________________________________________ AstroidManagerTest.test_namespace_package_pth_support ____________________________________________________

self = <astroid.tests.unittest_manager.AstroidManagerTest testMethod=test_namespace_package_pth_support>

    def test_namespace_package_pth_support(self):
        pth = 'foogle_fax-0.12.5-py2.7-nspkg.pth'
        site.addpackage(resources.RESOURCE_PATH, pth, [])
        pkg_resources._namespace_packages['foogle'] = []  # pylint: disable=no-member
    
        try:
            module = self.manager.ast_from_module_name('foogle.fax')
            submodule = next(module.igetattr('a'))
            value = next(submodule.igetattr('x'))
            self.assertIsInstance(value, astroid.Const)
            with self.assertRaises(exceptions.AstroidImportError):
                self.manager.ast_from_module_name('foogle.moogle')
        finally:
            del pkg_resources._namespace_packages['foogle'] # pylint: disable=no-member
>           sys.modules.pop('foogle')
E           KeyError: 'foogle'

astroid/tests/unittest_manager.py:139: KeyError
================================================ 2 failed, 649 passed, 92 skipped, 7 xfailed in 16.01 seconds ================================================
```

And as pytest.ini (not included in sdist tarball but needed by pytest) I used:
```
[pytest]
python_files = astroid/tests/unittest_*.py
norecursedirs = _build.* build
```

**Comment by brycepg** [comment] 2018-02-13 17:34
Bummer. So the issue for me was that the test data wasn't be properly modified in the installed astroid package (in `site-packages`) but instead, I think, in the local source `astroid` directory due to python's behavor of automatically including the current directory.

**Comment by PCManticore** [comment] 2018-06-20 06:38
Does this issue still reproduces for you folks?

**Comment by sebix** [comment] 2018-06-23 14:56
> Does this issue still reproduces for you folks?

Not this one for 1.6.5

**Comment by PCManticore** [comment] 2018-06-25 13:43
Alright, thanks for the comment @sebix ! Let's close this for now, if it still occurs we can reopen the issue.

**Closed by PCManticore** 2018-06-25 13:43 UTC
Labels: needs-reproduction
